# Generated by Django 5.1.2 on 2024-10-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_rename_quantity_product_total_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
